name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 17
          - java: 25
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v6.4.8
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           -J-Xmx4G
           "all scalafmtSbtCheck scalafmtCheckAll"
           test
           plugin2_12/scripted
    - if: "${{ matrix.java != '8' }}"
      run: sbt -v
           -J-Xmx4G
           plugin3/scriptedTestSbt2
    - run: rm -rf "$HOME/.ivy2/local"
