name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 16 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 21
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: coursier/cache-action@142d2738bd29f0eb9d44610828acb3a19809feab # v6.4.6
    - uses: sbt/setup-sbt@v1
    - run: sbt -v scalafmtSbtCheck "+ scalafmtCheckAll" test scripted
    - run: rm -rf "$HOME/.ivy2/local"
